add Linux commands course
nnct-jo-ken/kickstart pull request #2
Opened 2021-04-29 06:54 UTC by 1hPa

2021-04-29 13:05 UTC, Shibaken28 commented
ディレクトリの説明が欲しいです

2021-04-29 13:47 UTC, 1hPa commented
わかりました。作ります

2021-05-06 06:25 UTC, Shibaken28 approved these changes, later dismissed

2021-05-06 06:25 UTC, Shibaken28 commented on src/start-Linux-cmd/basic-cmd.md
> +**本記事はわからないことがあったときに毎回人に聞くことを推奨するものではありません**
部活で先輩に訊くのが怖くなるのでいらない

2021-05-06 06:25 UTC, Shibaken28 commented on src/start-Linux-cmd/basic-cmd.md
> +ﾆｲﾁｬﾝ「`..`は一つ下のdirectoryを指すから、`cd ..`と打つと、」
ディレクトリの層がだんだん下に行くイメージがあるので"上"のdirectoryの方がしっくりくる

2021-05-06 07:22 UTC, yu1hpa commented on src/start-Linux-cmd/basic-cmd.md
> +**本記事はわからないことがあったときに毎回人に聞くことを推奨するものではありません**
でも、なんでも聞いていいと思われたらこっちの身がもたないと思うし、
一言あるのはいいのでは？と思うんだけど。

2021-05-06 07:25 UTC, yu1hpa commented on src/start-Linux-cmd/basic-cmd.md
> +ﾆｲﾁｬﾝ「`..`は一つ下のdirectoryを指すから、`cd ..`と打つと、」
https://github.com/procon32/kickstart-programming/pull/2/commits/657d5dacd7b2a715198f7142a35ddff943b1a14d
修正した。

2021-05-10 06:48 UTC, hiroki-1219 requested changes

2021-05-10 06:48 UTC, hiroki-1219 commented on src/start-Linux-cmd/basic-cmd.md
> +ﾆｲﾁｬﾝ「`ls`はよく多様するよ！」
```suggestion
ﾆｲﾁｬﾝ「`ls`はよく多用するよ！」  
```
漢字ミスだと思います。

2021-05-10 07:18 UTC, hiroki-1219 approved these changes, later dismissed

2021-05-13 03:48 UTC, shun-shobon requested changes
思ったこと
- まずLinuxコマンドとはなにかの説明がない(J科生以外のことを考えていない)
- コマンドの構成についての説明がない(最初がコマンド名であるなど…)
- そもそもオプションとはなにかの説明がない(`-` or `--`を付けたらオプションであるという説明がない)
- manコマンドの説明がない(公式のマニュアルなので必ず紹介しておきたい)
- シングルクォーテーションとダブルクォーテーションについての説明がない
- リダイレクトとパイプラインについて説明するのなら標準入出力の説明がほしい

2021-05-13 03:48 UTC, shun-shobon commented on src/start-Linux-cmd/basic-cmd.md
> +**本記事はわからないことがあったときに毎回人に聞くことを推奨するものではありません**
Shibakenに同意、一番上にこれを記述するのは質問の萎縮を招く

2021-05-13 03:48 UTC, shun-shobon commented on src/start-Linux-cmd/basic-cmd.md
> +|-a        |全て表示            |ls -a |
｢全て｣の意味が不明(隠しファイルの概念についての説明がない)

2021-05-13 03:48 UTC, shun-shobon commented on src/start-Linux-cmd/basic-cmd.md
> +<!-- ![](../images/ls.png) -->
不要なので削除

2021-05-13 03:48 UTC, shun-shobon commented on src/start-Linux-cmd/basic-cmd.md
> +|-la       |-aと-lの組み合わせ  |ls -la|
確かに`-a`と`-l`の組み合わせではあるけども単にショートオプションは(多くの場合)複合可能というだけなのでオプションの説明として不適

2021-05-13 03:48 UTC, shun-shobon commented on src/start-Linux-cmd/basic-cmd.md
> +ﾆｲﾁｬﾝ「`ls`を使うときによく使うオプションは以下の通りだよ」
この説明だとオプションがこれだけしか無いというような誤解を招く
あくまで一例であるという記述が欲しい

2021-05-13 03:48 UTC, shun-shobon commented on src/start-Linux-cmd/basic-cmd.md
> +|-l        |ファイルの詳細も表示|ls -l |
ファイルの詳細とは？(詳しくは必要ないけどファイルサイズや所有者が表示されていることぐらいは記述して良いのでは？

2021-05-13 03:48 UTC, shun-shobon commented on src/start-Linux-cmd/basic-cmd.md
> +ex.) $HOME/
環境変数の説明が無いのでこれの意味が不明

2021-05-13 03:48 UTC, shun-shobon commented on src/start-Linux-cmd/basic-cmd.md
> +<!-- ![](../images/mkdir.png) -->
不要

2021-05-13 03:48 UTC, shun-shobon commented on src/start-Linux-cmd/basic-cmd.md
> +弟「今作ったディレクトリに移動したいんだけど・・・」
ディレクトリの移動とは？(カレントディレクトリの説明がない)

2021-05-13 03:48 UTC, shun-shobon commented on src/start-Linux-cmd/basic-cmd.md
> +<!-- ![](../images/cd.png) -->
不要

2021-05-13 03:48 UTC, shun-shobon commented on src/start-Linux-cmd/basic-cmd.md
> +<!-- ![](../images/touch.png) -->
不要

2021-05-13 03:48 UTC, shun-shobon commented on src/start-Linux-cmd/basic-cmd.md
> +ﾆｲﾁｬﾝ「（物などに）**タッチして生成してると考えると覚えやすいよ**」
もともとはファイルの更新日時の変更目的のコマンド(←この記述はあってもなくてもよいが`touch`はなんの略でもない)

2021-05-13 03:48 UTC, shun-shobon commented on src/start-Linux-cmd/basic-cmd.md
> +<!-- ![](../images/rm.png) -->
不要

2021-05-13 03:48 UTC, shun-shobon commented on src/start-Linux-cmd/basic-cmd.md
> +<!-- ![](../images/rm-r_1.png) -->
不要

2021-05-13 03:48 UTC, shun-shobon commented on src/start-Linux-cmd/basic-cmd.md
> +<!-- ![](../images/rm-r_2.png) -->
不要

2021-05-13 03:48 UTC, shun-shobon commented on src/start-Linux-cmd/basic-cmd.md
> +<!-- ![](../images/create-directory-file_mv.png) -->
不要

2021-05-13 03:48 UTC, shun-shobon commented on src/start-Linux-cmd/basic-cmd.md
> +<!-- ![](../images/mv.png) -->
不要

2021-05-13 03:48 UTC, shun-shobon commented on src/start-Linux-cmd/basic-cmd.md
> +<!-- ![](../images/mv_name.png) -->
不要

2021-05-13 03:48 UTC, shun-shobon commented on src/start-Linux-cmd/basic-cmd.md
> +<!-- ![](../images/cat.png) -->
不要

2021-05-13 03:48 UTC, shun-shobon commented on src/start-Linux-cmd/basic-cmd.md
> +<br>
これ is 何

2021-05-13 03:48 UTC, shun-shobon commented on src/start-Linux-cmd/basic-cmd.md
> +echo $SHELL
`$SHELL`変数の説明がない

2021-05-13 03:48 UTC, shun-shobon commented on src/start-Linux-cmd/basic-cmd.md
> +|\>> |追加で書き込み|
ファイル末尾に追加で書き込みのほうが分かりやすい

2021-05-13 03:48 UTC, shun-shobon commented on src/start-Linux-cmd/basic-cmd.md
> +<!-- ![](../images/echo.png) -->
不要

2021-05-13 03:48 UTC, shun-shobon commented on src/start-Linux-cmd/basic-cmd.md
> +> そこに、`written.txt`ファイルを作ろう。(PATH: $HOME/prac-kickstart/echo/written.txt)
PATHの説明がない

2021-05-13 03:48 UTC, shun-shobon commented on src/start-Linux-cmd/basic-cmd.md
> +有名なのは、`/bin/bash`、`/bin/zsh`、`/bin/fish`あたり
`/bin`にあるとは限らないため普通にbash,zsh,fishという説明でいいのでは？

2021-05-13 03:48 UTC, shun-shobon commented on src/start-Linux-cmd/basic-cmd.md
> +[^3]: `chmod`: 権限の付与
権限の付与ではなく権限の変更

2021-05-13 09:35 UTC, yu1hpa commented on src/start-Linux-cmd/basic-cmd.md
> +<br>
これとは。<br>のことだったら改行用

2021-05-14 14:58 UTC, yu1hpa commented
- [x] まずLinuxコマンドとはなにかの説明がない(J科生以外のことを考えていない)

- [x] コマンドの構成についての説明がない(最初がコマンド名であるなど…)

- [x] そもそもオプションとはなにかの説明がない(- or --を付けたらオプションであるという説明がない)

- [x] manコマンドの説明がない(公式のマニュアルなので必ず紹介しておきたい)

- [x] シングルクォーテーションとダブルクォーテーションについての説明がない

- [ ] リダイレクトとパイプラインについて説明するのなら標準入出力の説明がほしい
> 標準入力の説明を追加すると、一年生の頭がパンクする可能性がある...

2021-05-14 14:58 UTC, yu1hpa commented
https://github.com/procon32/kickstart-programming/pull/2#discussion_r631541197
これと、標準入力以外の問題は修正した。

2022-06-28 07:43 UTC, closed without merging