add wsl environment
nnct-jo-ken/kickstart pull request #3
Opened 2021-04-29 13:20 UTC by hiroki-1219

2021-05-06 06:06 UTC, Shibaken28 approved these changes, later dismissed

2021-05-06 07:08 UTC, yu1hpa requested changes

2021-05-06 07:08 UTC, yu1hpa commented on src/wsl_environment/chapter_1.md
> +WSL2を導入していきます。導入は<a href="https://docs.microsoft.com/ja-jp/windows/wsl/install-win10">Microsoftの公式ドキュメント</a>の手順で行っていきます。
```suggestion
WSL2を導入していきます。導入は[Microsoftの公式ドキュメント](https://docs.microsoft.com/ja-jp/windows/wsl/install-win10)の手順で行っていきます。
```
この書き方でリンク貼れない？

2021-05-06 07:08 UTC, yu1hpa commented on src/wsl_environment/chapter_1.md
> +<a href="https://wslstorestorage.blob.core.windows.net/wslblob/wsl_update_x64.msi">x64マシン用WSL2 Linux カーネル更新プログラムパッケージ</a>
```suggestion
<a href="https://wslstorestorage.blob.core.windows.net/wslblob/wsl_update_x64.msi">x64マシン用WSL2 Linux カーネル更新プログラムパッケージ</a>
```
上記のように\[文字列](url)でかける
以下も同様

2021-05-06 07:08 UTC, shun-shobon requested changes

2021-05-06 07:08 UTC, shun-shobon commented on src/wsl_environment/chapter_1.md
> +WSL2を導入していきます。導入は<a href="https://docs.microsoft.com/ja-jp/windows/wsl/install-win10">Microsoftの公式ドキュメント</a>の手順で行っていきます。
```suggestion
WSL2を導入していきます。導入は[Microsoftの公式ドキュメント](https://docs.microsoft.com/ja-jp/windows/wsl/install-win10)の手順で行っていきます。
```

2021-05-06 07:08 UTC, shun-shobon commented on src/wsl_environment/chapter_1.md
> +<a href="https://wslstorestorage.blob.core.windows.net/wslblob/wsl_update_x64.msi">x64マシン用WSL2 Linux カーネル更新プログラムパッケージ</a>
```suggestion
[x64マシン用WSL2 Linux カーネル更新プログラムパッケージ](https://wslstorestorage.blob.core.windows.net/wslblob/wsl_update_x64.msi)
```

2021-05-06 07:08 UTC, shun-shobon commented on src/wsl_environment/chapter_1.md
> +<a href="https://wslstorestorage.blob.core.windows.net/wslblob/wsl_update_arm64.msi">ARM64マシン用WSL2 Linux カーネル更新プログラムパッケージ</a>
```suggestion
[ARM64マシン用WSL2 Linux カーネル更新プログラムパッケージ](https://wslstorestorage.blob.core.windows.net/wslblob/wsl_update_arm64.msi)
```

2021-05-06 09:21 UTC, hiroki-1219 commented
URLの表記を変更、スタートメニューからUbuntuにアクセスする方法について画像を追加しました。
レビューをお願いします。

2021-05-06 10:26 UTC, yu1hpa approved these changes
私はOK.

2021-05-10 05:45 UTC, shun-shobon approved these changes
LTGM👍

2021-05-10 06:01 UTC, merged