Processing講座を追加
nnct-jo-ken/kickstart pull request #4
Opened 2021-05-06 05:32 UTC by Shibaken28

2021-05-06 06:53 UTC, shun-shobon requested changes
とりあえずここまで

2021-05-06 06:53 UTC, shun-shobon commented on book.toml
> +mathjax-support = true
EOF警察だ！(末尾に改行付けてね)

2021-05-06 06:53 UTC, shun-shobon commented on src/Processing/chapter_02.md
> +表にまとめてありますが，これらを頑張って覚える必要はありません．なぜなら，リファレンスをみればわかるからです．
リファレンスへのリンクがあったほうが親切かも

2021-05-06 06:53 UTC, shun-shobon commented on src/Processing/chapter_02.md
> +さて，お気づきの方もいるかもしれませんがこの```size(数字,数字);```というのは画面のサイズを指定しています．具体的には，```size(x,y);```というコードは画面の横の長さをx，縦の長さをyにする，という意味を持っています．
単語単位の場合はセミコロンは一つだけでいいよ
```suggestion
さて，お気づきの方もいるかもしれませんがこの`size(数字,数字);`というのは画面のサイズを指定しています．具体的には，`size(x,y);`というコードは画面の横の長さをx，縦の長さをyにする，という意味を持っています．
```

2021-05-06 06:53 UTC, shun-shobon commented on src/Processing/chapter_03.md
> +これでaという名前の箱が作られました．```int```は「整数を入れる箱を作れ」というおまじないです．
```suggestion
これでaという名前の箱が作られました．`int`は「整数を入れる箱を作れ」というおまじないです．
```

2021-05-06 06:53 UTC, shun-shobon commented on src/Processing/chapter_03.md
> +```a=6```の行が追加されました．これでaという名前の箱に6が入りました．注意するのはここでのイコール=は，等しいという意味ではありません．イコールの右にある数をaに「代入する」という意味です．
```suggestion
`a=6`の行が追加されました．これでaという名前の箱に6が入りました．注意するのはここでのイコール=は，等しいという意味ではありません．イコールの右にある数をaに「代入する」という意味です．
```

2021-05-06 06:53 UTC, shun-shobon commented on src/Processing/chapter_03.md
> +```print();```命令は，コンソールに表示させる命令です．
```suggestion
`print();`命令は，コンソールに表示させる命令です．
```

2021-05-06 06:53 UTC, shun-shobon commented on src/Processing/chapter_03.md
> +また，```int a```でaという名前の変数を作らなかった場合もエラーになります．
```suggestion
また，`int a`でaという名前の変数を作らなかった場合もエラーになります．
```

2021-05-06 06:53 UTC, shun-shobon commented on src/Processing/chapter_03.md
> +次のソースコードでは，```a=b```と```b=a```が同じ行にあり，同時に実行するように見えるかもしれませんが，そんなことはありません．```a=b;```のあとに改行したコードと全く同じ意味になります．
```suggestion
次のソースコードでは，`a=b`と`b=a`が同じ行にあり，同時に実行するように見えるかもしれませんが，そんなことはありません．`a=b;`のあとに改行したコードと全く同じ意味になります．
```

2021-05-06 06:53 UTC, shun-shobon commented on src/Processing/chapter_04.md
> +draw()に円を描くプログラムと```x=x+1```が入っています．draw()の中は繰り返されるのでxの値がどんどん増えていきます．print(x)を後ろにおいてみるとよくわかります．
```suggestion
draw()に円を描くプログラムと`x=x+1`が入っています．draw()の中は繰り返されるのでxの値がどんどん増えていきます．print(x)を後ろにおいてみるとよくわかります．
```

2021-05-06 06:53 UTC, shun-shobon commented on src/Processing/chapter_04.md
> +次のプログラムでは，x方向とy方向のそれぞれの速度を変数として定義しています．```x=x+2;y=y+1;```のように直接書きたくもなりますが，これを変数として宣言しておくことで汎用性が高いプログラムになります．
```suggestion
次のプログラムでは，x方向とy方向のそれぞれの速度を変数として定義しています．`x=x+2;y=y+1;`のように直接書きたくもなりますが，これを変数として宣言しておくことで汎用性が高いプログラムになります．
```

2021-05-06 06:53 UTC, shun-shobon commented on src/Processing/chapter_04.md
> +int x=300,y=300,vx=2,vy=1;
`vx`、`vy`が加速度だという説明がほしいかもしれない

2021-05-06 06:53 UTC, shun-shobon commented on src/Processing/chapter_05.md
> +|```a<=b```| aがb以下 |
```suggestion
|`a==b`| aとbが等しい |
|`a>b`| aがbより大きい |
|`a>=b`| aがb以上 |
|`a<b`| aがbより小さい |
|`a<=b`| aがb以下 |
```

2021-05-06 06:53 UTC, shun-shobon commented on src/Processing/chapter_05.md
> +また，条件を連ねたいときは```&&```を使います．"かつ"と読み替えることができます．次のプログラムはaが100以上，かつaが200未満，という条件になります．
```suggestion
また，条件を連ねたいときは`&&`を使います．"かつ"と読み替えることができます．次のプログラムはaが100以上，かつaが200未満，という条件になります．
```

2021-05-06 06:53 UTC, shun-shobon commented on src/Processing/chapter_05.md
> +"かつ"に対して，```||```[^1]は"または"を表す記号です．
```suggestion
"かつ"に対して，`||`[^1]は"または"を表す記号です．
```

2021-05-06 06:53 UTC, shun-shobon commented on src/Processing/chapter_05.md
> +> ```int score=任意の整数;```に対して，scoreが60未満の場合に「留年」と表示するプログラムを作成しなさい．
```suggestion
> `int score=任意の整数;`に対して，scoreが60未満の場合に「留年」と表示するプログラムを作成しなさい．
```

2021-05-06 06:53 UTC, shun-shobon commented on src/Processing/chapter_06.md
> +|```a<=b```| aがb以下 |
```suggestion
|`a==b`| aとbが等しい |
|`a>b`| aがbより大きい |
|`a>=b`| aがb以上 |
|`a<b`| aがbより小さい |
|`a<=b`| aがb以下 |
```

2021-05-06 06:53 UTC, shun-shobon commented on src/Processing/chapter_07.md
> +実は今まで使ってきた```rect()```や```fill()```，```print()```などは関数と呼ばれるものです．
```suggestion
実は今まで使ってきた`rect()`や`fill()`，`print()`などは関数と呼ばれるものです．
```

2021-05-06 06:53 UTC, shun-shobon commented on src/Processing/chapter_07.md
> +座標(x,y)を左上の頂点として，横a縦bの長さである長方形が描かれます．```print(S);```(Sは文字列)は，文字列Sがコンソールに表示されます．
```suggestion
例えば，`rect(x,y,a,b)`を実行した場合，
座標(x,y)を左上の頂点として，横a縦bの長さである長方形が描かれます．`print(S);`(Sは文字列)は，文字列Sがコンソールに表示されます．
```

2021-05-06 06:53 UTC, shun-shobon commented on src/Processing/chapter_08.md
> +そこで関数です．
```suggestion
そこで配列です．
```

2021-05-06 06:53 UTC, shun-shobon commented on src/Processing/chapter_09.md
> +    double a;
`double`急に出てきてない？

2021-05-06 06:53 UTC, shun-shobon commented on src/Processing/chapter_09.md
> +上のコードで，ballという名前のobject型の変数(のようなもの)が宣言されます．普通のint型などの変数とは違って```=new クラス名();```があることに注意です．そして，参照と代入は次のように行えます．
```suggestion
上のコードで，ballという名前のobject型の変数(のようなもの)が宣言されます．普通のint型などの変数とは違って`=new クラス名();`があることに注意です．そして，参照と代入は次のように行えます．

```

2021-05-06 06:57 UTC, Shibaken28 commented on src/Processing/chapter_09.md
> +    double a;
補足資料に説明があります

2021-05-06 06:57 UTC, yu1hpa requested changes

2021-05-06 06:57 UTC, yu1hpa commented on src/Processing/chapter_02.md
> +次のコードを入力してみましょう．最後のセミコロン;を忘れずに．
```suggestion
次のコードを入力してみましょう．最後のセミコロン(;)を忘れずに．
```

2021-05-06 06:57 UTC, yu1hpa commented on src/Processing/chapter_02.md
> +ウィンドウのどこかに三角形の再生マークのボタンがありますね．クリックすると実行されます．新しく画面(ウィンドウ)が表示されました．
```suggestion
ウィンドウに再生マークのボタンがありますね．クリックすると実行されます．新しく画面(ウィンドウ)が表示されました．
```

2021-05-06 06:57 UTC, yu1hpa commented on src/Processing/chapter_02.md
> +さて，お気づきの方もいるかもしれませんがこの```size(数字,数字);```というのは画面のサイズを指定しています．具体的には，```size(x,y);```というコードは画面の横の長さをx，縦の長さをyにする，という意味を持っています．
```suggestion
さて，お気づきの方もいるかもしれませんが，この```size(数字,数字);```というのは画面のサイズを指定しています．具体的には，```size(x,y);```というコードは画面の横の長さをx，縦の長さをyにする，という意味を持っています．
```

2021-05-06 06:57 UTC, yu1hpa commented on src/Processing/chapter_02.md
> +- Processing(コンピューター)に対して「画面描いて！」とか「正方形描いて！」みたいに命令しているので，しばしば「命令」と呼びます．
```suggestion
- Processingに対して「画面描いて！」とか「正方形描いて！」みたいに命令しているので，「命令」と呼びます．
```

2021-05-06 06:57 UTC, yu1hpa commented on src/Processing/chapter_02.md
> +[^2]:色の指定方法については補足資料をご覧ください
```suggestion
[^2]:色の指定方法については[補足資料](#補足資料)をご覧ください
```
リンクを作成したほうがいいと思う

2021-05-06 06:57 UTC, yu1hpa commented on src/Processing/chapter_03.md
> +箱です．何かを入れて保管(記憶)しておくことができます．
変数という言葉の意味について触れなくていいと思います。

2021-05-06 06:57 UTC, yu1hpa commented on src/Processing/chapter_03.md
> +### 箱の作り方
```suggestion
### 変数の宣言
```

2021-05-06 06:57 UTC, yu1hpa commented on src/Processing/chapter_03.md
> +これでaという名前の箱が作られました．```int```は「整数を入れる箱を作れ」というおまじないです．
```suggestion
これでaという名前の変数が作られました．```int```は「整数を入れる変数を作れ」という意味です．
```
おまじないって言葉を使わないほうがいいと思う。

2021-05-06 06:57 UTC, yu1hpa commented on src/Processing/chapter_03.md
> +### 箱に数を入れる
```suggestion
### 変数に数を入れる
```

2021-05-06 06:57 UTC, yu1hpa commented on src/Processing/chapter_03.md
> +このままだと，箱が空っぽなので数を入れます
```suggestion
このままだと，変数の中身が空っぽなので数を入れます
```

2021-05-06 06:57 UTC, yu1hpa commented on src/Processing/chapter_03.md
> +```a=6```の行が追加されました．これでaという名前の箱に6が入りました．注意するのはここでのイコール=は，等しいという意味ではありません．イコールの右にある数をaに「代入する」という意味です．
```suggestion
```a=6```の行が追加されました．これでaという名前の変数に6という数字が入りました．注意するのは，ここでのイコール(=)は，**等しいという意味ではありません**．イコールの右にある数をaに「**代入する**」という意味です．
```

2021-05-06 06:57 UTC, yu1hpa commented on src/Processing/chapter_03.md
> +このプログラムは少しトリッキーに見えるかもしれませんが，理路整然とシュミレーションしてみれば難しくありません．aという名前の箱にa+6の結果を代入するという意味ですが，このときのaは5ですので，aには5+6の11が代入されます．
```suggestion
このプログラムは少しトリッキーに見えるかもしれませんが，難しくありません．aという名前の変数にa+6の結果を代入するという意味ですが，このときのaは5ですので，aには5+6の11が代入されます．
```

2021-05-06 06:57 UTC, yu1hpa commented on src/Processing/chapter_03.md
> +>print(a,b);//a=5,b=3を得たい
```suggestion
>print(a,b);//a=3,b=5を得たい
```
typoだと思う。

2021-05-06 06:57 UTC, yu1hpa commented on src/Processing/chapter_03.md
> +print(a,b);
```suggestion
int a=5,b=3;
int t;
t=a //tにaの値を取っておく
a=b; //aに上書きされても
b=t; //tにもともとのaの値が残っている
print(a,b);
```

2021-05-06 06:57 UTC, yu1hpa commented on src/Processing/chapter_03.md
> +line(x-50,y+50,x+50,y+50);
```suggestion
```java
size(600,600);
-ellipse(300,300,200,200);
fill(0,0,0);
-ellipse(250,280,50,50);
-ellipse(350,280,50,50);
-line(250,350,350,350);
```
```
+int x=300,y=300;
size(600,600);
+ellipse(x,y,200,200);
fill(0,0,0);
+ellipse(x-50,y-20,50,50);
+ellipse(x+50,y-20,50,50);
+line(x-50,y+50,x+50,y+50);
```
差分を示して上げたほうがわかりやすいと思う。

2021-05-06 06:57 UTC, yu1hpa commented on src/Processing/chapter_04.md
> +急にvoid setup()やらdraw()が出てきて困惑するかもしれませんが，これはそういうものだと思ってください．
```suggestion
急にvoid setup()やらdraw()が出てきますが，これはこういうものです．
```

2021-05-06 06:57 UTC, yu1hpa commented on src/Processing/chapter_04.md
> +
ここに、残像がなくなったあとの画像を追加したほうがいいと思う。

2021-05-06 06:57 UTC, yu1hpa commented on src/Processing/chapter_04.md
> +int x=300,y=300;
```suggestion
int x=300;
int y=300;
```

2021-05-06 06:57 UTC, yu1hpa commented on src/Processing/chapter_04.md
> +int x=300,y=300,vx=2,vy=1;
```suggestion
int x=300;
int y=300;
int vx=2;
int vy=1;
```

2021-05-06 06:57 UTC, yu1hpa commented on src/Processing/chapter_04.md
> +次のプログラムでは，x方向とy方向のそれぞれの速度を変数として定義しています．```x=x+2;y=y+1;```のように直接書きたくもなりますが，これを変数として宣言しておくことで汎用性が高いプログラムになります．
```suggestion
次のプログラムでは，x方向とy方向のそれぞれの速度を変数として定義しています．

```x=x+2;y=y+1;```のように直接書きたくもなりますが，これを変数として宣言しておくことで汎用性が高いプログラムになります．
```

2021-05-06 06:57 UTC, yu1hpa commented on src/Processing/chapter_04.md
> +    x=mouseX;y=mouseY;
```suggestion
    x=mouseX;
    y=mouseY;
```
一行に書かずに改行しましょう！！

2021-05-06 06:57 UTC, yu1hpa commented on src/Processing/chapter_05.md
> +次の動きをするプログラムを作成できる
次の動きってどこ？？？

2021-05-06 06:57 UTC, yu1hpa commented on src/Processing/chapter_05.md
> +aとbが等しい時の条件式が=ではなく==であることに注意です．
```suggestion
aとbが等しい時の条件式が=ではなく**==**であることに注意です．
```
重要なので太文字

2021-05-06 06:57 UTC, yu1hpa commented on src/Processing/chapter_05.md
> +}
```suggestion
if(a==100){ // もし、aが100なら
  print("aは100です");
}
```

2021-05-06 06:57 UTC, yu1hpa commented on src/Processing/chapter_05.md
> +if(a>100){
```suggestion
if(a>100){ // aが100以上なら
```

2021-05-06 06:57 UTC, yu1hpa commented on src/Processing/chapter_05.md
> +if( 100<=a && a<200 ){
```suggestion
if( 100<=a && a<200 ){ // aが100以上200未満なら
```

2021-05-06 06:57 UTC, yu1hpa commented on src/Processing/chapter_05.md
> +"かつ"に対して，```||```[^1]は"または"を表す記号です．
```suggestion
"かつ"(`&&`)に対して，`||`[^1]は"または"を表す記号です．
```

2021-05-06 06:57 UTC, yu1hpa commented on src/Processing/chapter_05.md
> +elseは文字通りそうでないときの処理を書きます．
```suggestion
else（日本語: 他の）は文字通りそうでないときの処理を書きます．
```

2021-05-06 06:57 UTC, yu1hpa commented on src/Processing/chapter_05.md
> +int x=300,y=300;
```suggestion
int x=300;
int y=300;
```

2021-05-06 06:57 UTC, yu1hpa commented on src/Processing/chapter_05.md
> +int x=300,y=300;
```suggestion
int x=300;
int y=300;
```

2021-05-06 06:57 UTC, yu1hpa commented on src/Processing/chapter_06.md
> +##　while文
```suggestion
## while文
```

2021-05-06 06:57 UTC, yu1hpa commented on src/Processing/chapter_06.md
> +動作の確認をするために，一個ずつ命令の通りにしたがってシュミレーションしてみましょう(gif画像が欲しい)
```suggestion
動作の確認をするために，一個ずつ命令の通りにしたがってシュミレーションしてみましょう(gif画像が欲しい)
```
お気持ち表明だけじゃなくて貼れ笑

2021-05-06 14:15 UTC, Shibaken28 commented on src/Processing/chapter_04.md
> +int x=300,y=300,vx=2,vy=1;
加速度ではなくて速度です，コメントで変数の説明を書きました

2021-05-06 14:34 UTC, Shibaken28 commented on src/Processing/chapter_05.md
> +次の動きをするプログラムを作成できる
画像はります

2021-05-06 14:40 UTC, Shibaken28 commented on src/Processing/chapter_05.md
> +if(a>100){
より大きい　が適切です　直しました

2021-05-07 17:10 UTC, hiro-1219 requested changes
出すのが遅れてしまいました。ごめんなさい。

2021-05-07 17:10 UTC, hiro-1219 commented on src/Processing/chapter_02.md
> +次のコードを入力してみましょう．最後のセミコロン;を忘れずに．
```suggestion
次のコードを入力してみましょう．最後のセミコロン(;)を忘れずに．
```
このようにしたらどうでしょうか

2021-05-07 17:10 UTC, hiro-1219 commented on src/Processing/chapter_03.md
> +英語ができてました．エラー文といいます．これを読んで何がエラーの原因なのかを考えます．英語が読めなかったのでGoogle先生に任せます．
```suggestion
英語ができてました．エラー文といいます．これを読んで何がエラーの原因なのかを考えます．英語が読めなかったらGoogle先生に任せましょう．
```
読者目線にしたらどうでしょうか

2021-05-07 17:10 UTC, hiro-1219 commented on src/Processing/chapter_03.md
> +原因はaに何も値を入れていないことです．aという変数を作ったけれど，中身は空っぽなので表示できません！という意味です．変数の中身を使う場合は中身を入れてあるかに注意しましょう．
```suggestion
原因はaに何も値を入れていないことです．「aという変数を作ったけれど，中身は空っぽなので表示できません！」という意味です．変数の中身を使う場合は中身を入れてあるかに注意しましょう．
```
括弧などをつけて、どこがエラー文か分かりやすくしたらどうでしょうか

2021-05-07 17:10 UTC, hiro-1219 commented on src/Processing/chapter_05.md
> +演習5-2:
```suggestion
演習5-3:
```

2021-05-07 17:10 UTC, hiro-1219 commented on src/Processing/chapter_06.md
> +プログラム上でも意味は同じで，「Aの間Bを繰り返し実行」する場合は
```suggestion
プログラム上でも意味は同じで，「Aが正しい間，Bを繰り返し実行」する場合は
```
Aが真であることを強調して説明したらどうでしょうか。

2021-05-07 17:10 UTC, hiro-1219 commented on src/Processing/chapter_06.md
> +動作の確認をするために，一個ずつ命令の通りにしたがってシュミレーションしてみましょう(gif画像が欲しい)
```suggestion
動作の確認をするために，一個ずつ命令の通りにしたがってシュミレーションしてみましょう．
```
gif画像は入ってないので、消しておいたほうがいいと思います

2021-05-07 17:10 UTC, hiro-1219 commented on src/Processing/chapter_08.md
> +そこで関数です．
```suggestion
そこで配列です．
```
関数から配列にしてください

2021-05-07 17:10 UTC, hiro-1219 commented on src/Processing/chapter_08.md
> +
配列のインデックスを指定した要素のアクセス方法を書いていてください

2021-05-07 17:10 UTC, hiro-1219 commented on src/Processing/chapter_08.md
> +
インデックスが0から始まることを強調したらどうでしょうか

2021-05-07 17:10 UTC, hiro-1219 commented on src/Processing/chapter_08.md
> +配列は一度に処理をするのに非常に便利です(上の例だとすべてに1を加算している．
```suggestion
配列は一度に処理をするのに非常に便利です(上の例だとすべてに1を加算している．)
```
括弧を閉じておいてください

2021-05-07 17:10 UTC, hiro-1219 commented on src/Processing/chapter_08.md
> +```
クラスの説明と同様に配列の宣言にnewが必要なことを書いておくのはどうでしょうか

2021-05-07 17:10 UTC, hiro-1219 commented on src/Processing/chapter_09.md
> +上のコードで，ballという名前のobject型の変数(のようなもの)が宣言されます．普通のint型などの変数とは違って```=new クラス名();```があることに注意です．そして，参照と代入は次のように行えます．
```suggestion
上のコードで，ballという名前のobject型の変数(のようなもの)が宣言されます．普通のint型などの変数とは違って```=new クラス名();```があることに注意です．参照と代入は次のように行えます．

```
「そして，」は入れなくても大丈夫じゃないでしょうか。

2021-05-10 06:27 UTC, shun-shobon approved these changes

2021-05-10 06:27 UTC, shun-shobon commented on src/Processing/chapter_02.md
> +```rect(a,b,c,d)```を実行すると座標(a,b)を左上とする，横の長さc，縦の長さdの長方形が描かれます．
```suggestion
`rect(a,b,c,d)`を実行すると座標(a,b)を左上とする，横の長さc，縦の長さdの長方形が描かれます．
```

2021-05-10 06:27 UTC, shun-shobon commented on src/Processing/chapter_02.md
> +演習2-2：```rect(a,b,c,d)```のc,dは座標ではなく辺の長さです．辺の長さは400-100=300なので，cとdは300にする必要があります．
```suggestion
演習2-2：`rect(a,b,c,d)`のc,dは座標ではなく辺の長さです．辺の長さは400-100=300なので，cとdは300にする必要があります．
```

2021-05-10 06:27 UTC, shun-shobon commented on src/Processing/chapter_02.md
> +さきほどの```rect()```の他にも，三角形などを描く方法があります．
```suggestion
さきほどの`rect()`の他にも，三角形などを描く方法があります．
```

2021-05-10 06:27 UTC, shun-shobon commented on src/Processing/chapter_02.md
> +表にまとめてありますが，これらを頑張って覚える必要はありません．なぜなら，リファレンス(https://processing.org/reference/)をみればわかるからです．
```suggestion
表にまとめてありますが，これらを頑張って覚える必要はありません．なぜなら，[リファレンス](https://processing.org/reference/)をみればわかるからです．
```

2021-05-10 06:27 UTC, shun-shobon commented on src/Processing/chapter_02.md
> +| ```stroke(r,g,b)``` | この命令の後に描く図形の輪郭は色(r,g,b)で塗られる |
```suggestion
| `point(x,y)`| 座標(x,y)に点をうつ |
| `line(x1,y1,x2,y2)` | 座標(x1,y1)と座標(x2,y2)が両端の線分を描く |
| `ellipse(x,y,a,b)` | 座標(x,y)を中心に横軸がa，縦軸がbの楕円を描く[^1] |
| `triangle(x1,y1,x2,y2,x3,y3)` | (x1,y1) と (x2,y2) と (x3,y3) をつなぐ三角形を描く|
| `fill(r,g,b)` | この命令の後に描く図形の内部は色(r,g,b)[^2]で塗られる |
| `stroke(r,g,b)` | この命令の後に描く図形の輪郭は色(r,g,b)で塗られる |
```

2021-05-10 06:27 UTC, shun-shobon commented on src/Processing/chapter_03.md
> +これでaという名前の変数が作られました．```int```は「整数を入れる変数を作れ」という意味です．
```suggestion
これでaという名前の変数が作られました．`int`は「整数を入れる変数を作れ」という意味です．
```

2021-05-10 06:27 UTC, shun-shobon commented on src/Processing/chapter_03.md
> +|割った余り[^4]|```%```|```a=25%4```|```1```|
```suggestion
|足し算|`+`|`a=24+41`|`65`|
|引き算|`-`|`a=5-12`|`-7`|
|掛け算|`*`|`a=25*8`|`200`|
|割り算[^3]|`/`|`a=76/19`|`4`|
|割った余り[^4]|`%`|`a=25%4`|`1`|
```

2021-05-10 06:27 UTC, shun-shobon commented on src/ProcessingOther/color.md
> +| ```(000,255,255)```| 水 |
```suggestion
| `(000,000,000)`| 黒 |
| `(255,255,255)`| 白 |
| `(255,000,000)`| 赤 |
| `(000,255,000)`| 緑 |
| `(000,000,255)`| 青 |
| `(255,255,000)`| 黄 |
| `(255,000,255)`| 紫 |
| `(000,255,255)`| 水 |
```

2021-05-10 06:27 UTC, shun-shobon commented on src/ProcessingOther/operator.md
> +|右にビットシフト|```>>```|```a=4>>1```|```2```|
```suggestion
|AND|`&`|`a=1&3`|`1`|
|OR|`|`|`a=1|3`|`3`|
|XOR|`^`|`a=1^3`|`2`|
|左にビットシフト|`<<`|`a=1<<3`|`8`|
|右にビットシフト|`>>`|`a=4>>1`|`2`|
```

2021-05-10 06:27 UTC, shun-shobon commented on src/ProcessingOther/scratch.md
> +| ![a](img/def.png "a") | ```void greeting(string name){print(name);}``` |
```suggestion
| ![a](img/if.png "a") | `if(a>50){}` |
| ![a](img/for.png "a") | `for(int i=0;i<10;i++){}` |
| ![a](img/and.png "a") | `50<a && a<100` |
| ![a](img/else.png "a") | `if(a==50){}else{}` |
| ![a](img/while.png "a") | `a=0;while(!a==50){a=a+1;}` |
| ![a](img/def.png "a") | `void greeting(string name){print(name);}` |
```

2021-05-10 06:27 UTC, shun-shobon commented on src/ProcessingOther/var.md
> +chapter2では```int```で整数をいれる変数を作れることがわかりました．これによって作られた変数をint型変数，といいます．あるいは，整数が入るので単に整数型とも言います．
```suggestion
chapter2では`int`で整数をいれる変数を作れることがわかりました．これによって作られた変数をint型変数，といいます．あるいは，整数が入るので単に整数型とも言います．
```

2021-05-10 06:27 UTC, shun-shobon commented on src/ProcessingOther/var.md
> +上のサンプルのように，```int```の代わりに```float```を使うと小数を代入することができます．
```suggestion
上のサンプルのように，`int`の代わりに`float`を使うと小数を代入することができます．
```

2021-05-10 06:28 UTC, shun-shobon requested changes
間違えた

2021-05-10 07:15 UTC, shun-shobon approved these changes

2021-05-10 07:16 UTC, hiroki-1219 approved these changes

2021-05-10 07:16 UTC, yu1hpa approved these changes

2021-05-10 07:16 UTC, merged