Processing courses
nnct-jo-ken/kickstart pull request #7
Opened 2021-06-13 06:46 UTC by Shibaken28

2021-06-21 08:55 UTC, hiroki-1219 approved these changes

2021-06-21 08:57 UTC, shun-shobon approved these changes

2021-06-21 08:57 UTC, shun-shobon commented on src/ProcessingChallenge/sqrt.md
> +## 二分探索
二分探索 is 何

2021-06-21 08:57 UTC, shun-shobon requested changes
間違えた

2021-06-23 07:37 UTC, Shibaken28 commented on src/ProcessingChallenge/sqrt.md
> +## 二分探索
後で書きます

2021-06-23 07:37 UTC, hiroki-1219 submitted a review, later dismissed

2021-06-24 03:22 UTC, yu1hpa approved these changes, later dismissed

2021-06-27 08:51 UTC, shun-shobon approved these changes, later dismissed

2022-04-26 14:27 UTC, yu1hpa commented on src/Processing/chapter_05.md
> +次のif文では，``score<60``の条件を満たさなかった場合，``else``の方が実行されます．
`score<60`, `else`で囲めると思う

2022-04-26 14:36 UTC, yu1hpa commented on src/Processing/chapter_06.md
> +- ``GAME OVER``と表示される
https://github.com/procon32/kickstart-programming/pull/7#discussion_r858783769
と同様のことができる

2022-04-26 14:36 UTC, yu1hpa commented on src/Processing/chapter_06.md
> +上の例では，``p=hp-attack``の時点で``hp=-4``で``hp>0``を満たしていませんが，その後の``print(hp)``は実行されています．これは，中括弧内の一連の処理を終えてから，まだループするかどうかの判定``hp>0``を行っているからです．
ここも https://github.com/procon32/kickstart-programming/pull/7#discussion_r858783769
と同様のことができる

2022-04-26 14:36 UTC, yu1hpa commented on src/Processing/chapter_06.md
> +[^2]:実は，変数``i``のスコープは異なります．詳しくは[補足資料/変数の詳しい話](../ProcessingOther/var.md) をご覧ください
https://github.com/procon32/kickstart-programming/pull/7#discussion_r858783769
と同様のことができる

2022-04-26 14:36 UTC, yu1hpa commented on src/Processing/chapter_06.md
> +演習6-1: 5050です．``100*(100+1)/2``と計算できます．
https://github.com/procon32/kickstart-programming/pull/7#discussion_r858783769

2022-04-26 14:36 UTC, yu1hpa commented on src/Processing/chapter_06.md
> +draw()内の最後(``}``の前)に``if(x>=50)x=0;``を追加してみましょう
https://github.com/procon32/kickstart-programming/pull/7#discussion_r858783769

2022-04-27 03:32 UTC, shun-shobon requested changes

2022-04-27 03:32 UTC, shun-shobon commented on src/Processing/chapter_05.md
> +> 演習5-1に加えて，scoreが101を以上の場合も"留年"と表示するプログラムを作成しなさい．
```suggestion
> 演習5-1に加えて，scoreが101以上の場合も"留年"と表示するプログラムを作成しなさい．
```

2022-04-27 07:42 UTC, shun-shobon approved these changes
LGTM!

2022-04-27 08:00 UTC, Shibaken28 commented
マージします

2022-04-27 08:00 UTC, merged